### PR TITLE
Uaf 3794 : fix PREQ calculation exception when PO encumber dollar amount is 0

### PR DESCRIPTION
**Pull request by lshyu**
These code are from KFS3, and only made some changes to make it work on KFS6.   I tested generate SQL from the change log file, but 'test changelog' build is currently not working to verify it is really working.

### CODE REVIEW

**Comment by heather-lo** [comment]
Lin-Long, I'd like to see your liquibase changeset successfully tested before this is merged.

**Comment by ghost** [comment]
Hi Lin-Long,
We only use Liquibase for data structure changes. For adding new parameters, changes in parameter value, etc. we add SQL to our DB upgrade process. See UAF-92 and associated Jiras. Also, your commit should reference your actual Jira number, UAF-3794 , not Uaf 3794. 
Thanks,
Julie

**Comment by lshyu** [comment]
Julie,

   I checked UAF-92 and I did see sub task UAF-2044.  So, the process is to create a sub task which paste my sql and ask someone to add to upgrade scripts.  Please let me know who should be assigned to when I creatged this jira.  I think my commit comment is OK. It's the the auto generated description for pull request change it to Uaf 3794.   I will make sure it reflects the jira number for future pull request.  Thanks.

**Comment by lshyu** [comment]
Since I deleted change log and also waiting sub task to complete. So, I'll close this request and recreate after sub task is complete.

**Pull request closed without merging**
