### PR TITLE
UAF-43 UAF-2567 Allow Disapprove on ObjectSubTypeCode

### PR DESCRIPTION
**Pull request by leahasullivan**
Added code to allow disapprove on ObjectSubTypeCode Routing for REQ documents to the PurapConstants.java. Added the RoleTypeServiceCallBack for the objectSubTypeCodeRoleTypeService to the spring-coa-bus-exports.xml  

Also fixed merge conflicts with development branch and indents.

### CODE REVIEW

**Comment by ghost** [comment]
The ObjectSubTypeCode routing status changes to PurapConstants.RequisitionStatuses class look good, but the ObjectSubTypeCode routing status changes to PurapConstants.PurchaseOrderStatuses class still need to be made. Let me know if you have any questions.

**Comment by ghost** [comment]
Initial Review complete.

**Comment by leahasullivan** [comment]
I was confused between the comments on UAF-2512 Jira and the KFS3 commit.  Adding for purchase order statuses.

**Comment by leahasullivan** [comment]
Added the necessary code for PurapConstants.PurchaseOrderStatuses just as I did for RequisitionStatuses.

**Comment by ghost** [comment]
Looks good! Will discuss with BAs whether this can be a late merge.

**Pull request merged**
