### PR TITLE
UAF-2935 - Adding corrected XML per WorkflowData.xsd specified in Rice.

### PR DESCRIPTION
**Pull request by sskinner**
Replaced invalid elements with those specified in the Rice schemata at:
- RICE/impl/src/main/resources/schema/WorkflowData.xsd
- RICE/impl/src/main/resources/schema/RuleAttribute.xsd
  Misty has tested these specific changes in the TST environment, which means all files in the workflow directory have now been ingested successfully after this most recent data refresh.

### CODE REVIEW

**Comment by ghost** [comment]
This does not match delivered workflow for this document. See (starting at line 290): https://github.com/ua-eas/kfs/blob/ua-development/kfs-core/src/main/config/workflow/070_purchasing_accounts_payable/PurchasingAccountsPayableTransactionalDocuments.xml.

I think once Will has resolved the issues that he was having ingesting the DB upgrade workflow that this change will no longer be needed.

**Comment by sskinner** [comment]
That file is not valid XML for our version of Rice, as WorkflowData.xsd dictates. There is no longer an "attributes" element, thus so will fail validation, and so will be impossible to ingest with our version numbers, unless we revert to an older version of the schema. Regardless of what Will does on the DB backend, this will still be invalid XML, since it appears the validation is performed against the schema as found in the rice-impl lib.

**Comment by sskinner** [comment]
Ok, looking at it again, I see several forms located under DocumentType.xsd, including the form I use above, _and_ the form that the old version has. The odd thing is that if we use the old way, that the DB will be hit, and that the old values in the XML are not currently in the related table.

Oh wait... I think it is now conclusive -- I just looked these up in the KFS3 DB, and the values are present there (they aren't in 6, it didn't occur to me till now to compare the two). So there it is, that's how this must have been able to load before. It's just odd, since even the file you make mention of above, has the same new elements I changed to in this PR (to be fair, it contains both the old and new). Also, this new form seems to work fine, as Misty's testing passed all of the PO tests. I'm wondering if there aren't just two ways to do the same thing, or if the testing procedure is missing the case to flex this functionality.

**Comment by sskinner** [comment]
Closing due to discovering that the root cause was due to a missing upgrade step.

**Pull request closed without merging**
